name: dash-terminal
version: 1.0.0
description: LXC Terminal PWA with native tmux integration - Go PTY server + xterm.js frontend
type: lxc-terminal-pwa

# 🤖 AI START HERE - READ THIS FIRST!
ai_instructions: |
  STOP! Do not start coding yet!

  1. FIRST: Check if dppm app is available:
     command: dppm status project dash-terminal

  2. IF dppm available: Follow dppm task order
  3. IF no dppm: Read docs/tasklist.md for task breakdown
  4. ALWAYS start with T1.1 project-setup (critical priority)

  NEVER start with PWA or frontend - backend foundation first!

metadata:
  author: AI-S-Tools
  license: MIT
  repository: https://github.com/AI-S-Tools/dash-terminal
  homepage: https://github.com/AI-S-Tools/dash-terminal

dependencies:
  runtime:
    - go: ">=1.21"
    - lxc: ">=5.0"
    - tmux: ">=3.0"

  packages:
    - github.com/gorilla/websocket: "v1.5.0"
    - github.com/creack/pty: "v1.1.18"

scripts:
  start: "node src/index.js"
  dev: "node --watch src/index.js"
  build: "npm run lint && npm test"
  test: "node --test"
  lint: "eslint src/"

structure:
  src:
    - index.js: Main entry point
    - dashboard.js: Dashboard controller
    - widgets/:
      - system.js: System monitoring widget
      - tasks.js: Task management widget
      - git.js: Git repository status widget
      - network.js: Network monitoring widget
      - logs.js: Log viewer widget
    - utils/:
      - config.js: Configuration loader
      - theme.js: Theme management
      - data.js: Data fetching utilities

  config:
    - default.yaml: Default configuration
    - themes/:
      - dark.yaml: Dark theme
      - light.yaml: Light theme
      - cyberpunk.yaml: Cyberpunk theme

  tests:
    - dashboard.test.js: Dashboard tests
    - widgets.test.js: Widget tests

features:
  - Real-time system monitoring (CPU, Memory, Disk, Network)
  - Git repository status and branch information
  - Task/TODO management with persistence
  - Log file monitoring and filtering
  - Customizable themes and layouts
  - Keyboard shortcuts for navigation
  - API monitoring and health checks
  - Weather information widget
  - Docker container status
  - Process monitoring

configuration:
  layout:
    grid: true
    columns: 12
    rows: 12

  refresh_rates:
    system: 1000
    network: 2000
    git: 5000
    weather: 600000

  shortcuts:
    quit: "q"
    help: "h"
    refresh: "r"
    theme_toggle: "t"
    focus_next: "tab"
    focus_previous: "shift+tab"

environment:
  DPPM_THEME: dark
  DPPM_LOG_LEVEL: info
  DPPM_CONFIG_PATH: ./config/default.yaml
  DPPM_DATA_DIR: ~/.dppm/dash-terminal

build:
  output: dist/
  minify: false
  sourcemaps: true